import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import path from 'node:path';
import fs from 'node:fs';

const root = path.resolve(import.meta.dirname, '..');
const executablePath = process.env.APEX_BROWSER || (process.platform === 'win32' ? 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe' : undefined);
const browser = await chromium.launch({ headless: true, ...(executablePath ? { executablePath } : {}) });
const page = await browser.newPage({ viewport: { width: 1600, height: 1100 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
async function done() { await page.waitForFunction(() => !document.querySelector('#demo').disabled); assert.equal(await page.locator('#status').evaluate(e => e.classList.contains('error')), false, await page.locator('#status').textContent()); }
try {
  await page.goto(process.env.APEX_VIEWER || 'http://127.0.0.1:8765/?mode=workbench');
  await page.locator('#demo').click(); await done();
  await page.locator('#chart svg rect.bar').first().click(); await done();
  assert.match(await page.locator('#inspector').textContent(), /reservations/);
  await page.locator('#fork').click(); await done();
  const forkStatus=await page.locator('#status').textContent();
  await page.locator('#resource').selectOption('M0'); await done();
  assert.equal((await page.locator('#status').textContent()).split(' · ')[0],forkStatus.split(' · ')[0]);
  await page.locator('#resource').selectOption(''); await done();
  await page.locator('#apply').click(); await done();
  await page.locator('#repair').click(); await done();
  await page.locator('#compare').click(); await done();
  assert.match(await page.locator('#comparison').textContent(), /changed_count/);
  await page.locator('#objective').click(); await done();
  await page.locator('#validate').click(); await done();
  assert.match(await page.locator('#inspector').textContent(), /"valid": true/);
  await page.locator('#file').setInputFiles(path.join(root, 'examples/shift-factory.json')); await done();
  await page.locator('#create').click(); await done();
  assert.ok(await page.locator('#chart svg rect.pre').count() > 0);
  assert.ok(await page.locator('#chart svg rect.post').count() > 0);
  assert.ok(await page.locator('#chart svg rect.reserve').count() > 0);
  await page.locator('#factory').click(); await done();
  await page.locator('[data-view="routes"]').click(); await done();
  assert.equal(await page.locator('.route-card').count(),5);
  await page.locator('.route-card select').first().selectOption('standard');
  await page.locator('.route-card button').first().click(); await done();
  assert.match(await page.locator('.route-card').first().textContent(),/Selected: standard/);
  await page.screenshot({ path: path.join(root, 'docs/reports/viewer-routes.png'), fullPage: true });
  await page.locator('[data-view="jobs"]').click(); await done();
  assert.match(await page.locator('#model-content').textContent(),/ORDER-1/);
  await page.locator('#group-type').selectOption('orders'); await done();
  await page.screenshot({ path: path.join(root, 'docs/reports/viewer-orders.png'), fullPage: true });
  await page.locator('[data-view="rules"]').click(); await done();
  assert.match(await page.locator('#model-content').textContent(),/order_weighted_tardiness/);
  await page.locator('[data-view="schedule"]').click(); await done();
  await page.locator('#connect-agent').click();
  assert.match(await page.locator('#mcp-endpoint').textContent(),/\/mcp$/);
  await page.locator('#connect-agent').click();
  await page.locator('#chart svg rect.bar').first().click(); await done();
  await page.screenshot({ path: path.join(root, 'docs/reports/viewer.png'), fullPage: true });
  const sharedUrl=page.url();
  await page.reload(); await done();
  assert.match(await page.locator('#inspector').textContent(),/ORDER-1/);
  assert.equal(page.url(),sharedUrl);
  await page.locator('#down-resource').selectOption('CUT1');
  await page.locator('#down-start').fill('0');
  await page.locator('#down-end').fill('900');
  await page.locator('#outage').click(); await done();
  assert.match(await page.locator('#comparison').textContent(),/changed operations/);
  await page.locator('[data-view="rules"]').click(); await done();
  assert.match(await page.locator('#model-content').textContent(),/900/);

  await page.locator('#demo').click(); await done();
  await page.locator('#search-settings summary').click();
  await page.locator('#search-evaluations').fill('24');await page.locator('#search-seconds').fill('0');await page.locator('#search-population').fill('8');await page.locator('#search-workers').fill('2');await page.locator('#search-selection').selectOption('pareto');
  await page.locator('#improve').click();await done();await page.locator('[data-view="search"]').click();await done();
  assert.match(await page.locator('#model-content').textContent(),/trainer_plus_portfolio/);
  assert.equal(await page.locator('#train, #plus').count(),0);
  assert.match(await page.locator('#model-content').textContent(),/Combined improvement/);
  await page.screenshot({path:path.join(root,'docs/reports/v0.5-combined-viewer.png'),fullPage:true});
  assert.match(await page.locator('#model-content').textContent(),/24 evaluations/);
  assert.ok(await page.locator('.goal-editor input').count()>0);
  await page.locator('.goal-editor input').nth(1).fill('2');
  await page.locator('#apply-goals').click();await done();
  assert.match(await page.locator('#model-content').textContent(),/Goal → construction proxies/);
  await page.screenshot({path:path.join(root,'docs/reports/viewer-search.png'),fullPage:true});
  await page.locator('#improve').click();await done();assert.match(await page.locator('#model-content').textContent(),/trainer_plus_portfolio/);
  await page.locator('[data-view="schedule"]').click();await done();
  await page.locator('#freeze-resource').selectOption('M0');await page.locator('#freeze-start').uncheck();await page.locator('#freeze-order').uncheck();
  await page.locator('#freeze').click();await done();
  assert.ok(await page.locator('.freeze-zone[data-dimensions="resource"]').count()>0);
  assert.ok(await page.locator('.lock-badge').count()>0);assert.doesNotMatch(await page.locator('#chart').textContent(),/T · R/);
  await page.locator('#freeze-start').check();await page.locator('#freeze-mode').check();await page.locator('#freeze-order').check();await page.locator('#freeze').click();await done();
  assert.ok(await page.locator('.fixed-start').count()>0);assert.ok(await page.locator('.fixed-sequence').count()>0);
  await page.locator('.bar.fixed-start').first().click();await done();assert.match(await page.locator('#inspector').textContent(),/Start fixed at/);assert.match(await page.locator('#inspector').textContent(),/Primary resource fixed/);
  await page.screenshot({path:path.join(root,'docs/reports/viewer-locks.png'),fullPage:true});
  const locksUrl=page.url();await page.reload();await done();assert.ok(await page.locator('.freeze-zone').count()>0);

  const mode={id:'standard',primary:'M0',phases:[{id:'work',work:100,interruption:'calendar_resumable',requirements:[{resource:'M0',retain:true}]}]};
  const runningProblem={schema_version:'apex.v3.3',id:'synthetic-running-block-ui',horizon:1000,resources:[{id:'M0',calendar:[{start:0,end:1000}]}],tasks:['RUN','NEXT','FREE'].map(id=>({id,modes:[mode]})),locks:[{kind:'order',resource:'M0',tasks:['RUN','NEXT'],consecutive:true}]};
  runningProblem.tasks[0].execution={mode:'standard',as_of:30,actual:{id:'actual',task:'RUN',role:'actual',mode:'standard',start:0,end:30,segments:[{phase:'work',start:0,end:30,work:30}],reservations:[{resource:'M0',start:0,end:30,amount:1}]},remaining_work:{work:70}};
  async function invoke(name,arguments_){const response=await fetch(new URL('/api/tool',sharedUrl),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,arguments:arguments_})});const value=await response.json();assert.ok(response.ok,JSON.stringify(value));return value;}
  const runningInput=await invoke('problem.import',{problem:runningProblem});const runningPlan=await invoke('schedule.plus',{scenario_id:runningInput.scenario_id,options:{iterations:12,budget_ms:0,plus:{workers:2,depth:3}}});
  await page.goto(runningPlan.viewer_url);await done();assert.match(await page.locator('.lock-badge[data-task="RUN"]').textContent(),/B RUN/);assert.ok(await page.locator('.actual').count()>0);assert.match(await page.locator('.fixed-sequence title').textContent(),/Consecutive block/);
  await page.locator('.bar').first().click();await done();assert.match(await page.locator('#inspector').textContent(),/Started operation/);
  await page.screenshot({path:path.join(root,'docs/reports/viewer-running-block.png'),fullPage:true});
  await page.goto(sharedUrl); await done();
  await page.setViewportSize({ width: 800, height: 900 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.deepEqual(errors, []);
  fs.writeFileSync(path.join(root, 'docs/reports/viewer-tests.json'), JSON.stringify({ passed: true, url:sharedUrl, locks_url:locksUrl, browser: 'Chromium/Edge headless', flows: ['demo', 'inspect', 'fork', 'patch', 'repair', 'compare', 'objective', 'validate', 'file import', 'conditional activity display', 'production order expansion', 'route pin and replan', 'jobs and orders and rules views', 'agent connection panel', 'task deep link reload', 'structured outage fork and comparison', '800px viewport', 'parallel trainer and Pareto controls', 'objective edit and retrain', 'Fast Planner Plus', 'resource-only freeze', 'time/resource/mode/order freeze badges and inspector', 'freeze deep link reload', 'running actual work and consecutive block markers with Plus'], page_errors: errors }, null, 2));
  console.log('Viewer workflows passed; screenshot saved.');
} finally { await browser.close(); }
