"""Generate tiny Codex discovery entries from canonical developer skills."""

import argparse
import re

from repository import ROOT


def entries(root=ROOT):
    for source in sorted((root / "dev/skills").glob("*/SKILL.md")):
        text = source.read_text(encoding="utf-8")
        match = re.match(r"\A---\nname: ([a-z0-9-]+)\ndescription: ([^\n]+)\n---\n", text)
        if not match or match[1] != source.parent.name:
            raise ValueError(f"Invalid developer skill metadata: {source}")
        name, description = match.groups()
        body = (f"---\nname: {name}\ndescription: {description}\n---\n\n"
                f"# {name}\n\n"
                "This entry is generated by `dev/scripts/sync_skills.py`.\n"
                f"Read and follow [the canonical developer skill](../../../dev/skills/{name}/SKILL.md).\n"
                "Resolve that skill's relative links against its own directory.\n")
        yield root / ".agents/skills" / name / "SKILL.md", body
        metadata = source.parent / "agents/openai.yaml"
        if metadata.exists():
            # Invocation policy must reach the discoverable skill, not just its source.
            yield root / ".agents/skills" / name / "agents/openai.yaml", metadata.read_text(encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    changed = []
    for destination, content in entries():
        if not destination.exists() or destination.read_text(encoding="utf-8") != content:
            changed.append(destination.relative_to(ROOT).as_posix())
            if not args.check:
                destination.parent.mkdir(parents=True, exist_ok=True)
                destination.write_text(content, encoding="utf-8", newline="\n")
    if args.check and changed:
        parser.exit(1, "Skill discovery entries are stale: " + ", ".join(changed) + "\n")
    count = len(list((ROOT / "dev/skills").glob("*/SKILL.md")))
    print(f"Developer skill entries {'checked' if args.check else 'synchronized'}: {count}")


if __name__ == "__main__":
    main()
