"""Build the public wiki from an explicit Markdown allowlist, without network or AI."""

import argparse
import json
from pathlib import Path, PurePosixPath
import re
import subprocess
from urllib.parse import quote, unquote, urlsplit


MARKER = "<!-- Generated by scripts/build_wiki.py; edit the source repository. -->"
MANIFEST = ".apex-wiki-pages.json"
INLINE_LINK = re.compile(
    r'(!?\[(?:[^\]\\]|\\.)*\]\(\s*)'
    r'(<[^>\n]+>|(?:[^\s()\\]|\\.|\([^()\n]*\))+)'
    r'(\s*(?:"[^"\n]*"|\'[^\'\n]*\'|\([^()\n]*\))?\s*\))'
)
REFERENCE = re.compile(r'^( {0,3}\[[^\]\n]+\]:\s*)(<[^>\n]+>|\S+)', re.M)
TOKENS = re.compile(
    r'(?P<fence>^ {0,3}(?P<delimiter>`{3,}|~{3,})[^\n]*\n.*?^ {0,3}(?P=delimiter)[ \t]*(?:\n|$))'
    + r'|(?P<link>' + INLINE_LINK.pattern + r')'
    + r'|(?P<reference>' + REFERENCE.pattern + r')'
    + r'|(?P<code>(?P<ticks>`+).*?(?P=ticks)(?!`))', re.M | re.S
)


def git(root, *args):
    return subprocess.check_output(["git", "-C", str(root), *args], text=True).strip()


def title(text):
    match = re.search(r"^# ([^\n]+)", text, re.M)
    if not match:
        raise ValueError("Every wiki page needs a level-one heading")
    return match[1].strip().strip("#").strip()


def transform_markdown(text, rewrite):
    """Rewrite inline/reference destinations while leaving code examples untouched."""
    def replace(token):
        if token["fence"] or token["code"]:
            return token[0]
        match = INLINE_LINK.fullmatch(token[0]) if token["link"] else REFERENCE.fullmatch(token[0])
        destination = match[2]
        angle = destination.startswith("<")
        value = destination[1:-1] if angle else destination
        value = rewrite(value, match[1].startswith("!"))
        return match[1] + (f"<{value}>" if angle else value) + (match[3] if match.lastindex == 3 else "")
    return TOKENS.sub(replace, text)


def build(root, repository, revision):
    root = root.resolve()
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9][A-Za-z0-9_.-]*", repository):
        raise ValueError("Expected an owner/repository name")
    if not re.fullmatch(r"[a-f0-9]{40}", revision):
        raise ValueError("Source revision must be a full Git commit SHA")
    tracked = set(git(root, "ls-files", "-z").split("\0"))
    groups = json.loads((root / "scripts/wiki-pages.json").read_text(encoding="utf-8"))
    pages = {}
    slugs = set()
    for entries in groups.values():
        for source, slug in entries.items():
            if source in pages or slug.casefold() in slugs or not re.fullmatch(r"[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*", slug):
                raise ValueError(f"Duplicate or invalid page: {source}")
            source_path = root / source
            if source not in tracked or not source.endswith(".md") or not source_path.resolve().is_relative_to(root):
                raise ValueError(f"Wiki source must be tracked Markdown inside the repository: {source}")
            if any(part.is_symlink() for part in [source_path, *source_path.parents] if part != root):
                raise ValueError(f"Symlink source is not allowed: {source}")
            pages[source] = slug
            slugs.add(slug.casefold())
    if pages.get("docs/README.md") != "Home":
        raise ValueError("docs/README.md must map to Home")
    repo_url = f"https://github.com/{repository}"
    wiki_url = f"{repo_url}/wiki"
    rendered, titles = {}, {}
    for source, slug in pages.items():
        text = (root / source).read_text(encoding="utf-8")
        titles[source] = title(text)

        def rewrite(destination, image=False):
            parsed = urlsplit(destination)
            if parsed.scheme or parsed.netloc:
                if parsed.scheme not in ("", "http", "https", "mailto"):
                    raise ValueError(f"Unsupported link scheme in {source}")
                return destination
            if not parsed.path:
                return destination
            if "\\" in destination or parsed.path.startswith("/"):
                raise ValueError(f"Use repository-relative links in {source}: {destination}")
            target = (root / PurePosixPath(source).parent / unquote(parsed.path)).resolve()
            if not target.is_relative_to(root):
                raise ValueError(f"Link escapes repository in {source}: {destination}")
            relative = target.relative_to(root).as_posix()
            if relative not in tracked and not any(p.startswith(relative + "/") for p in tracked):
                raise ValueError(f"Missing or untracked link in {source}: {destination}")
            if target.is_symlink() or not target.exists():
                raise ValueError(f"Invalid link in {source}: {destination}")
            suffix = ("?" + parsed.query if parsed.query else "") + ("#" + parsed.fragment if parsed.fragment else "")
            if relative in pages and not image:
                return f"{wiki_url}/{pages[relative]}{suffix}"
            if image:
                return f"https://raw.githubusercontent.com/{repository}/{revision}/{quote(relative)}{suffix}"
            kind = "tree" if target.is_dir() else "blob"
            return f"{repo_url}/{kind}/{revision}/{quote(relative)}{suffix}"

        body = transform_markdown(text, rewrite)
        notice = (
            f"{MARKER}\n\n"
            f"> Published from the [source document]({repo_url}/blob/{revision}/{quote(source)}). "
            f"[Propose an edit]({repo_url}/edit/main/{quote(source)}) through a pull request; "
            "direct wiki edits are replaced by the next publication.\n\n"
        )
        rendered[f"{slug}.md"] = notice + body.rstrip() + "\n"
    sidebar = [MARKER, "", "**APEX documentation**", ""]
    for group, entries in groups.items():
        sidebar.extend([f"**{group}**", ""])
        sidebar.extend(f"- [{titles[source]}]({wiki_url}/{slug})" for source, slug in entries.items())
        sidebar.append("")
    rendered["_Sidebar.md"] = "\n".join(sidebar)
    rendered["_Footer.md"] = (
        f"{MARKER}\n\n[Source repository]({repo_url}) · "
        f"[Revision {revision[:7]}]({repo_url}/commit/{revision}) · "
        f"[License]({repo_url}/blob/{revision}/LICENSE)\n"
    )
    return rendered


def write_output(output, rendered):
    """Replace only previously managed pages; preserve unrelated wiki content/history."""
    if output.is_symlink():
        raise ValueError("Output must not be a symlink")
    output = output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    manifest = output / MANIFEST
    if manifest.is_symlink():
        raise ValueError("Managed manifest must not be a symlink")
    previous = json.loads(manifest.read_text(encoding="utf-8")) if manifest.exists() else []
    if not isinstance(previous, list) or any(not isinstance(name, str) or not re.fullmatch(r"[A-Za-z0-9_-]+\.md", name) for name in previous):
        raise ValueError("Invalid managed-page manifest")
    # Validate every affected path before any writes or deletion.
    for name in set(previous) | set(rendered):
        path = output / name
        if path.is_symlink() or (path.exists() and not path.is_file()):
            raise ValueError(f"Unsafe output path: {name}")
        if path.exists() and not path.read_text(encoding="utf-8").startswith(MARKER):
            raise ValueError(f"Refusing to overwrite an unmanaged wiki page: {name}")
    for name in set(previous) - set(rendered):
        (output / name).unlink(missing_ok=True)
    for name, text in rendered.items():
        (output / name).write_text(text, encoding="utf-8", newline="\n")
    manifest.write_text(json.dumps(sorted(rendered), indent=2) + "\n", encoding="utf-8", newline="\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--repository", default="qunevo/apex")
    parser.add_argument("--revision")
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    try:
        rendered = build(args.root, args.repository, args.revision or git(args.root, "rev-parse", "HEAD"))
        if args.output:
            output = args.output.resolve()
            root = args.root.resolve()
            if output == root or root.is_relative_to(output) or output.is_relative_to(root / ".git"):
                raise ValueError("Output must be a separate build directory or wiki checkout")
            write_output(args.output, rendered)
        print(f"Wiki validation passed: {len(rendered) - 2} public pages, sidebar, footer and local link targets.")
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        parser.exit(1, f"Wiki build failed: {error}\n")


if __name__ == "__main__":
    main()
